Add: JWT 토큰 생성 로직
YAPP-18th/Android-Team-1-Backend pull request #16
Opened 2021-04-26 14:54 UTC by Catnap421

https://daddyprogrammer.org/post/636/springboot2-springsecurity-authentication-authorization/

이거보면서 우선 JWT 토큰 생성 로직까지만 작성해봤는데, UserEntity를 추가하는 부분이 있더라고.
그 부분은 MemberEntity를 수정해서 작성하면 될까??

2021-04-27 06:54 UTC, NaLDo627 requested changes
> https://daddyprogrammer.org/post/636/springboot2-springsecurity-authentication-authorization/
> 
> 이거보면서 우선 JWT 토큰 생성 로직까지만 작성해봤는데, UserEntity를 추가하는 부분이 있더라고.
> 그 부분은 MemberEntity를 수정해서 작성하면 될까??

응응 사용자 로그인을 위해서 테스트 해야 하는 경우에는 너말대로  Member 엔티티 사용하면 될거야! 아마 repository 통해서 회원 조회하는 로직이 필요할텐데, 이 부분 테스트할때 MockBean 등을 사용해서 Mock으로 실제 DB 사용하지 않게 분리하면 될거야, 너무 어려울거 같으면 얘기해!

고생 많았어!
추가로 작성한 코드들에 대해서 테스트 코드도 작성해줘 ㅎㅎ
스프링 시큐리티 테스트 관련은 mockmvc 구성해서 하면 될꺼야! (https://catchdream.tistory.com/194)
JWT 가 원하는대로 생성 되는지, 임의의 사용자에 대해서 ROLE이 제대로 부여되는지 테스트 하면 될듯 해
나도 면접준비하느라 바빴는데 이제부터 개발이랑 인프라 구축 관련해서 고민해봐야겠다.

2021-04-27 06:54 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/core/jwt/JwtTokenProvider.java
> +    }
이건 public일 이유가 있는거야?

2021-04-27 06:54 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/core/jwt/JwtAuthenticationFilter.java
> +        }
token이 null이라면 이 조건을 그냥 패스하지 않을까??

2021-04-27 08:16 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/core/jwt/JwtTokenProvider.java
> +    }
private으로 바꾸도록 할게!

2021-04-27 08:25 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/core/jwt/JwtAuthenticationFilter.java
> +        }
음 이부분은 다른 레퍼런스 보고 따라한 거긴한데, 다들 저렇게 처리를 했더라고.. 형이 말하고자 하는게 token이 null일 때 따로 처리를 해주는 부분이 필요하다는 거 맞나???

2021-04-27 08:40 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/core/jwt/JwtAuthenticationFilter.java
> +        }
응응 그게 더 직관적일듯! 아니면 validateToken 메서드에서 널체크 해도 되구

2021-04-28 06:45 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/core/jwt/JwtAuthenticationFilter.java
> +        }
형 말대로 validateToken 메서드 좀 살펴보니까 null이면 false를 반환하도록 되어있더라고! 그래서 삭제했어!

2021-04-28 08:45 UTC, Catnap421 reviewed
일단 테스트 코드는 작성하지 않았는데, 임시로 컨트롤러 만들어서 해보니까 만들어지기는 하는 거 같아. mockBean을 처음 써봐서 그건 좀 더 삽질해볼게! 
우선 현재까지 작성한 코드에서 모르는 거 코멘트 달아뒀어!

2021-04-28 08:45 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/core/jwt/JwtTokenProvider.java
> +    }
여기 userDetails.getAuthorities()가 Member 클래스에 구현되어 있는데, 지금은 null을 리턴하는데, 어떻게 처리해야할지 감이 안와.. role 멤버 변수 만들어서 저장해야하지 않아? [Member 65-68 참고!](https://github.com/YAPP-18th/Android-Team-1-Backend/pull/16/commits/283361280d7f76899035078d387cc9bd9a046360#diff-de79df091658bdc8150391da49cc180cf175ef2f3e91ea99fd445f1800e60ef6R65-R68)

2021-04-28 09:56 UTC, NaLDo627 reviewed
그러면 테스트는 지금 작성중인거야??
나도 스프링 시큐리티를 많이 써보지 않아서, 더더욱 테스트로 우리가 원하는대로 동작하는지 검증해 봐야 할 것 같아.. 그래야 나중이 편해져 ㅎㅎ

2021-04-28 09:56 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/core/jwt/JwtTokenProvider.java
> +    }
이부분은 권한 설정하는 부분으로 알고있는데, 당장 권한 관련된 부분은 없으니까 안넣어줘도 되지 않을까??
[여기](https://docs.spring.io/spring-security/site/docs/4.2.20.RELEASE/apidocs/org/springframework/security/authentication/UsernamePasswordAuthenticationToken.html)서 생성자 보면 아예 파라미터를 안 받을 수도 있는데, 이건 나도 삽질하면서 알아봐야할듯..

2021-04-28 09:56 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/member/entity/Member.java
> +public class Member implements UserDetails {
이건 나도 좀 헷갈리는 부분인데,
멤버 엔티티를 UserDetails로 활용하는게 맞는 선택인건가..?
엔티티는 도메인 계층에서 사용되는 녀석이고, UserDetails는 컨트롤러 계층에서 사용되어질텐데, 이 두 개를 같이 사용해도 되는지 모르겠어. 따로 컨트롤러 계층에서 사용할 사용자 객체를 만드는게 어떨까 싶은데, 한편으로는 두 객체(엔티티 <-> UserDetails 구현체)간의 변환 과정때문에 코드양이 더 많아질거 같기도 하고... 어떻게 생각해?

2021-04-29 02:48 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/member/entity/Member.java
> +public class Member implements UserDetails {
나도 따로 만드는 게 좋을 거 같아! 그리고 테스트 작성 중이긴 한데, 무얼 테스트 해야할지를 잘 모르겠네.. 일단 UserDetails 따로 빼서 코드 다시 작성해놓을게!

2021-04-29 04:03 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/member/entity/Member.java
> +public class Member implements UserDetails {
응응 따로 만드는걸로 하자!
단순히 로그인한 사용자와 비로그인한 사용자가 로그인해야하는 리소스에 접근할 수 있는지, JWT가 잘 생성되는지 정도만 테스트하면 될 거같아!

2021-04-29 04:11 UTC, Catnap421 reviewed
Member에서 UserDetails를 구현하는 것 대신 CustomUserDetails라는 것으로 따로 빼고, 멤버 변수로 Member를 갖도록 처리했어!

2021-04-29 04:11 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/core/jwt/JwtTokenProvider.java
> +    }
요 부분에 대해서 알아보니까, 보통은 Member 클래스(UserDetails를 구현한)에 List로 Role 멤버 변수를 설정해서, DB에 각 사용자마다 role을 저장해서 가져오는 방식이더라고. 혹은 생성할 때, 파라미터를 받지 않고, AuthenticationManager라는 것에 인증 권한을 위임해서 처리하거나! (https://jeong-pro.tistory.com/205) 
이렇게까지 하는 건 비효율적인거 같아서, userDetatils.getAuthorites()를 호출하면 "ROLE_USER"를 담은 authorities 객체를 반환하도록 하드 코딩처리 할까 하는데 괜찮을까?

2021-04-29 04:52 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/core/jwt/JwtTokenProvider.java
> +    }
응응 우선은 그렇게 해도 될 거 같아!

2021-04-29 04:56 UTC, NaLDo627 reviewed
CustomUserDetails에 Member 를 속성으로 추가하는건 기발한 것 같아!
테스트는 단순하게 로그인한 사용자와 비로그인한 사용자가 로그인해야하는 리소스에 접근할 수 있는지, JWT가 잘 생성되는지 정도만 테스트하면 될 거같아!

2021-04-29 06:55 UTC, Catnap421 reviewed
[MockBean](https://velog.io/@sproutt/MockBean%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%ED%86%B5%ED%95%A9Controller%ED%85%8C%EC%8A%A4%ED%8A%B8)
로그인한 사용자 검증 계속 작성 해보고 있는데, MemberDetailService를 MockBean으로 만들면 멤버 변수인 MemberRepository가 null로 되고... 잘 모르겠네...
Autowired로 하면 Bean 객체 잘 주입되는데..

2021-04-29 09:51 UTC, NaLDo627 commented
> [MockBean](https://velog.io/@sproutt/MockBean%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%9C-%ED%86%B5%ED%95%A9Controller%ED%85%8C%EC%8A%A4%ED%8A%B8)
> 로그인한 사용자 검증 계속 작성 해보고 있는데, MockBean으로 만들면 MemberDetailService를 MockBean으로 만들면 MemberDetailService의 멤버 변수인 MemberRepository가 null로 되고... 잘 모르겠네...
> Autowired로 하면 Bean 객체 잘 주입되는데..

MockBean 으로 만드는데 MemberDetailService 멤버를 알필요가 있는거야?? when().then() 으로 출력할 값을 지정해 줄 수 있을텐데..
지금은 주석처리 해놓았는데 난 [이렇게](https://github.com/NaLDo627/BankSystemKakao/blob/master/src/test/java/com/kakaointerntask/bank/controller/BankUserControllerTests.java) 테스트 했었어!

2021-04-29 13:50 UTC, Catnap421 commented
테스트 성공!! 내가 member 객체를 빌더로 잘못만들고 있어서 에러가 떴던 거였어 ㅠㅠ

2021-04-29 14:14 UTC, NaLDo627 approved these changes
굿!!  andExpect 로 성공하는거 확실히 보여주면 될거같아! 수고했어!

2021-04-29 14:14 UTC, NaLDo627 commented on src/test/java/net/mureng/mureng/web/HomeControllerTest.java
> +        );
andExpect도 붙여줘!

2021-04-29 14:14 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/member/service/MemberDetailsService.java
> +public class MemberDetailsService implements UserDetailsService {
클래스이름을 차라리 UserDetailsServiceImpl 로 바꾸는게 어떨까??

2021-04-29 14:37 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/member/service/MemberDetailsService.java
> +public class MemberDetailsService implements UserDetailsService {
아 그게 좀 더 좋겠다! 오케오케 바꾸고 머지할게~

2021-04-29 14:43 UTC, merged