Add: 도메인 클래스 생성
YAPP-18th/Android-Team-1-Backend pull request #2
Opened 2021-04-04 16:28 UTC by Catnap421

ERD에 맞춰서 한 번 도메인 클래스 추가했으니 확인하고 PR해줘!

2021-04-05 10:34 UTC, NaLDo627 requested changes
변수명은 lowerCamelCase 로 부탁해!
테이블 컬럼 명이랑 일치하려면 @column 어노테이션으로 지정해야 할거야

2021-04-05 10:34 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/domain/badge/Badge.java
> +    private Long badge_id;
변수명은 lowerCamelCase 로 부탁해!
테이블 컬럼 명이랑 일치하려면 @Column 어노테이션으로 지정해야 할거야

2021-04-05 10:34 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/web/Controller.java
> +}
이거는 테스트용으로 만든거야??

2021-04-05 10:49 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/domain/badge/BadgeAccomplished.java
> +    private Long member_id;
badge_id랑 member_id 둘다 외래키인데 @ManyToOne 어노테이션이라던가 아예 외부랑 연결시켜주는게 없는거 같아!
만약 너무 어려우면 내가 수정할게 ㅎㅎ

2021-04-05 11:57 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/domain/badge/Badge.java
> +    private Long badge_id;
오케오케 한번 형 의견 들어보고 싶었어

2021-04-05 11:58 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/web/Controller.java
> +}
응응 디렉토리 만들고 깃헙에 올리려면 파일 있어야하길래 ㅋㅋㅋ

2021-04-05 11:58 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/domain/badge/BadgeAccomplished.java
> +    private Long member_id;
한번 해보고 어려우면 도움 요청할게 ㅎㅎ 이참에 배워봐야지

2021-04-05 12:03 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/domain/badge/BadgeAccomplished.java
> +    private Long member_id;
연관관계에 대해서는 [여기](https://kihoonkim.github.io/2017/01/27/JPA(Java%20ORM)/3.%20JPA-%EC%97%94%ED%8B%B0%ED%8B%B0%20%EB%A7%A4%ED%95%91/)서 읽어보면 좋을 것 같고,
복합키는 [여기](https://lng1982.tistory.com/286)서 @Embeddable 사용하면 좋을 것 같아!

2021-04-05 12:04 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/domain/badge/Badge.java
> +    private Long badge_id;
오키오키
그리고 궁금한게 Setter나 Builder가 없는데 값은 어떻게 셋팅할거야..? ㅎㅎ

2021-04-06 11:50 UTC, NaLDo627 requested changes
Data 어노테이션은 가급적 지양하는걸로 하자 ㅎㅎ
그리고 NOT NULL 속성에 @column(nullable = false) 어노테이션 붙여줘..! ㅎ.ㅎ

2021-04-06 11:50 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/domain/badge/Badge.java
> +@Data
Data 어노테이션에는 ToString 어노테이션이 포함되어 있는데, 양방향 관계에서 사용하면 중복 참조가 날수도 있어..!
그래서 개인적으론 Data어노테이션 잘 안써 ㅎㅎ Setter 만 붙여줘도 될 것 같아!

2021-04-06 14:40 UTC, Catnap421 commented on src/main/java/net/mureng/mureng/domain/badge/Badge.java
> +@Data
아하 그렇구나! 한 수 더 배우고 갑니당~

2021-04-08 06:16 UTC, NaLDo627 reviewed
굿굿 ㅎㅎ 근데 Setter를 아예 제거했던데, 만약 내용을 수정해야 할 일이 생기면 어떻게 할거야?.?

2021-04-08 06:16 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/domain/member/MemberAttendance.java
> +    private MemberAttendancePK id;
얘는 복합키가 아니라 단일키이고, Member테이블에 대해 식별관계인데, onetoone 관계로 시도했는데 안되서 이렇게 시도한거야?.?

2021-04-08 06:18 UTC, NaLDo627 commented on src/main/java/net/mureng/mureng/domain/member/MemberAttendance.java
> +    private MemberAttendancePK id;
아 슬랙을 지금 봤어 ㅎㅎ 오케

2021-04-08 06:20 UTC, NaLDo627 approved these changes
수고했어! ㅎㅎ 나도 직접 실행해보고 수정사항 반영할게~!

2021-04-08 06:20 UTC, merged